version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stdout
  logFile:
    class: amaterasu.cli.utils.logging.AllUsersTimedRotatingFileHandler
    level: INFO
    filename: /var/log/amaterasu/amaterasu.log
    formatter: simple
    when: midnight
  debugLog:
    class: amaterasu.cli.utils.logging.AllUsersTimedRotatingFileHandler
    level: DEBUG
    filename: /var/log/amaterasu/amaterasu-debug.log
    when: midnight
    formatter: simple
loggers:
  amaterasu:
    level: DEBUG
    handlers: [console, logFile, debugLog]
    propagate: no
root:
  level: ERROR
  handlers: [console, logFile]